### ISSUE TITLE
update

### ISSUE THREAD

**Issue by futuremoneybtc** [Jamerson1000/million-python#1]
please update your code with multiprocessing

**Comment by Jamerson1000** [comment]
Yes, i will

**Comment by futuremoneybtc** [comment]
> Yes, i will

Thanks if you have done right now i will check with multi cores and will post benchmark here of different bits

**Comment by Jamerson1000** [comment]
Is done! :)

**Comment by futuremoneybtc** [comment]
OMG! too fast.. All the best for your GPU version coding.. did you decide any name for this cracker ??

**Comment by Jamerson1000** [comment]
??
